spring:
  profiles:
    active: dev
  application:
    name: mmo

app:
  initial-data:
    auto-import: true
  telegram:
    bot:
      token: ${TELEGRAM_TOKEN}
      username: H2_FB_Bot
    channel:
        id: ${CHANNEL_ID}
